apiVersion: v1
kind: Pod
spec:
  containers:
    - name: rpmdev-fedora
      image: stephen001/rpmdev-fedora:30
      tty: true
      command:
        - cat
      volumeMounts:
        - name: packages
          mountPath: /data
        - name: package-signing-key
          mountPath: /secret
          readOnly: true
  securityContext:
    fsGroup: 1000
  volumes:
    - name: packages
      persistentVolumeClaim:
        claimName: packages
    - name: package-signing-key
      secret:
        secretName: package-signing-key
