apiVersion: v1
kind: Pod
spec:
  containers:
    - name: rpmdev-fedora
      image: stephen001/rpmdev-fedora:rawhide
      tty: true
      command:
        - cat
      volumeMounts:
        - name: upstream-releases
          mountPath: /releases
        - name: fedora-packages
          mountPath: /packages
  securityContext:
    fsGroup: 1000
  volumes:
    - name: upstream-releases
      persistentVolumeClaim:
        claimName: upstream-releases
    - name: fedora-packages
      persistentVolumeClaim:
        claimName: fedora-packages
