apiVersion: v1
kind: Pod
spec:
  containers:
    - name: fedora
      image: fedora:30
      tty: true
      command:
        - cat
      volumeMounts:
        - name: upstream-releases
          mountPath: /releases
  securityContext:
    fsGroup: 1000
  volumes:
    - name: upstream-releases
      persistentVolumeClaim:
        claimName: upstream-releases
