apiVersion: v1
kind: Pod
spec:
  containers:
    - name: busybox
      image: busybox:latet
      imagePullPolicy: Always
      tty: true
      command:
        - cat
      volumeMounts:
        - name: packages
          mountPath: /data
  securityContext:
    fsGroup: 1000
  volumes:
    - name: packages
      persistentVolumeClaim:
        claimName: packages